### ISSUE TITLE
Recommend Youtube channels for learning 

### ISSUE THREAD

**Issue by Whizkevina** [ictgft2/LearningResources#4]
A Little of Everything (Web Dev, Computer Science, and Musings

**Comment by MeetD99** [comment]
Can you assign it to me, I can contribute to this Issue.

**Comment by Whizkevina** [comment]
@MeetD99 You can go ahead to contribute, just follow the contributing guide.

**Comment by MeetD99** [comment]
Hey @Whizkevina , I have successfully created a PR, Kindly Review it and lemme know of any Changes. Thank You!
